# Generated by Django 4.2 on 2023-04-27 16:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('levelupapi', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Game_Type',
            new_name='Gametype',
        ),
    ]
